### ISSUE TITLE
Error when installing requirements: ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by mateusscheper** [arc53/DocsGPT#119]
Hi! 

I'm getting an error when trying to install the requirements:
```
$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting aiohttp==3.8.3
  Using cached aiohttp-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Requirement already satisfied: aiosignal==1.3.1 in /home/mateus/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.3.1)
Collecting alabaster==0.7.13
  Using cached alabaster-0.7.13-py3-none-any.whl (13 kB)
Requirement already satisfied: async-timeout==4.0.2 in /home/mateus/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (4.0.2)
Collecting attrs==22.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting Babel==2.11.0
  Using cached Babel-2.11.0-py3-none-any.whl (9.5 MB)
Collecting blobfile==2.0.1
  Using cached blobfile-2.0.1-py3-none-any.whl (73 kB)
Collecting certifi==2022.12.7
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer==2.1.1
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting dataclasses-json==0.5.7
  Using cached dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
Collecting docutils==0.19
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting faiss-cpu==1.7.3
  Using cached faiss_cpu-1.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
Collecting filelock==3.9.0
  Using cached filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting Flask==2.2.2
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Requirement already satisfied: frozenlist==1.3.3 in /home/mateus/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (1.3.3)
Collecting greenlet==2.0.2
  Using cached greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
Collecting huggingface-hub==0.12.0
  Using cached huggingface_hub-0.12.0-py3-none-any.whl (190 kB)
Collecting idna==3.4
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting imagesize==1.4.1
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting itsdangerous==2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting joblib==1.2.0
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting langchain==0.0.81
  Using cached langchain-0.0.81-py3-none-any.whl (225 kB)
Collecting lxml==4.9.2
  Using cached lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
Collecting MarkupSafe==2.1.2
  Using cached MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting marshmallow==3.19.0
  Using cached marshmallow-3.19.0-py3-none-any.whl (49 kB)
Collecting marshmallow-enum==1.5.1
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Requirement already satisfied: multidict==6.0.4 in /home/mateus/.local/lib/python3.10/site-packages (from -r requirements.txt (line 29)) (6.0.4)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting nltk==3.8.1
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting numpy==1.24.1
  Using cached numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting openai==0.26.4
  Using cached openai-0.26.4.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 804, in parse_config_files
          parse_configuration(
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 158, in parse_configuration
          meta.parse()
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 498, in parse
          section_parser_method(section_options)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 469, in parse_section
          self[name] = value
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 222, in __setitem__
          value = parser(value)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 599, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 422, in _parse_attr
          module = importlib.import_module(module_name)
        File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-ln6t2r3l/openai_1d7e7b9794c9445ca030b2c87d53ada0/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Python and pip versions:
```
$ python3 --version
Python 3.10.6
$ pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

Am I missing something? 
Thanks!

**Comment by dartpain** [comment]
try running `pip install aiohttp`
