### ISSUE TITLE
could you please truncate prompt before send it out?

### ISSUE THREAD

**Issue by chinesewebman** [arc53/DocsGPT#145]
I converted a book, when ask question about it, often get error below:

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 8291 tokens (8035 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
This model's maximum context length is 4097 tokens, however you requested 8291 tokens (8035 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

meybe truncate the prompt into less than 3800 is good before send it out?

**Comment by chinesewebman** [comment]
or how about put 2500 in prompt, 1500 in completion? the answers are often being cut offed even when choosing the demo document.

**Comment by chinesewebman** [comment]
below is the detail error msg:
-----
Traceback (most recent call last):
  File "/root/DocsGPT-main/application/app.py", line 133, in api_answer
    result = chain({"query": question})
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/vector_db_qa/base.py", line 153, in _call
    )
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/combine_documents/map_reduce.py", line 139, in combine_docs
    results = self.llm_chain.apply(
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 91, in apply
    ) -> Tuple[List[str], Optional[List[str]]]:
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py", line 59, in generate
    response = self.llm.generate(prompts, stop=stop)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 128, in generate
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 125, in generate
    output = self._generate(prompts, stop=stop)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 217, in _generate
    return await _completion_with_retry(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 178, in completion_with_retry
    import openai
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 176, in _completion_with_retry
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 6980 tokens (6724 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
This model's maximum context length is 4097 tokens, however you requested 6980 tokens (6724 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by chinesewebman** [comment]
2 emails sent, attachments are the "bad" index files, and there is "bad" question to reproduce the error too :-)

**Comment by dartpain** [comment]
Thank you! I recieved everything and work on it later today or tommorow

**Comment by dartpain** [comment]
Deployed a solution, checked on your data, it should work well, please check

**Comment by chinesewebman** [comment]
the problem is gone forever, many thanks!

**Comment by chinesewebman** [comment]
thank you for being so nice!
