### ISSUE TITLE
module 'tiktoken' has no attribute 'encoding_for_model'

### ISSUE THREAD

**Issue by 137-rick** [arc53/DocsGPT#183]
5001 service return error:

Traceback (most recent call last):
  File "/data/www/docsgpt/application/app.py", line 192, in api_answer
    result = chain({"query": question})
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/vector_db_qa/base.py", line 160, in _call
    answer, _ = self.combine_documents_chain.combine_docs(docs, question=question)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/combine_documents/map_reduce.py", line 143, in combine_docs
    return self._process_results(results, docs, token_max, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/combine_documents/map_reduce.py", line 173, in _process_results
    num_tokens = length_func(result_docs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 83, in prompt_length
    return self.llm_chain.llm.get_num_tokens(prompt)
  File "/usr/local/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 313, in get_num_tokens
    enc = tiktoken.encoding_for_model(self.model_name)
AttributeError: module 'tiktoken' has no attribute 'encoding_for_model'
module 'tiktoken' has no attribute 'encoding_for_model'

**Comment by 137-rick** [comment]
change application requirement.txt 
langchain==0.0.116

now work

**Comment by dartpain** [comment]
Done, updated, thank you!

**Comment by isbkch** [comment]
Going back to 0.0.116 throws this error when attempting to start `app.py`

```st
Traceback (most recent call last):
  File "/Users/x_bakouil1/Dev/ml/docsGPT/app/application/app.py", line 14, in <module>
    from langchain.chains import LLMChain, ConversationalRetrievalChain
ImportError: cannot import name 'ConversationalRetrievalChain' from 'langchain.chains' (/opt/homebrew/lib/python3.11/site-packages/langchain/chains/__init__.py)

Process finished with exit code 1
```
