### ISSUE TITLE
Uploads fixes

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#186]
- [ ] 1) In order to get new entry on the drop down have to refresh it
- [ ] 2) text going out of its drop-down box

**Comment by Thayalan21** [comment]
Hello which file type should be uploaded to the drop down. Because I've tried pdf and rst both aren't working

**Comment by ajaythapliyal** [comment]
> Hello which file type should be uploaded to the drop down. Because I've tried pdf and rst both aren't working

Hey @Thayalan21 can you tell us more about the issue you are facing?  What do you see?

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/226821989-cfeb55b6-a03e-4a5e-b60a-1ad50a5846f6.png)
 This is the error i am facing . In the front end i've tried to upload the pdf and also rst file format for training my documents.But it just shows this pop message and nothing happened

**Comment by Thayalan21** [comment]
@ajaythapliyal 
![image](https://user-images.githubusercontent.com/104500045/226823538-6c0cbc42-48c0-4c4a-8d63-4b004affb6ab.png)

This is the error i am facing . In the front end i've tried to upload the pdf and also rst file format for training my documents.But it just shows this pop message and nothing happened

**Comment by Thayalan21** [comment]
[image: image.png]

**Comment by Thayalan21** [comment]
This is the error i am facing.I tried to upload documents in the upload
section but it pops file uploading but nothing happens afterwards

**Comment by dartpain** [comment]
Did you launch worker? 
Please describe how you launched docsGPT and what steps did you go through

**Comment by Thayalan21** [comment]
Also which file type should we actually upload a pdf or a rst?

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/227071796-84d53699-b375-431e-9a51-51f7d9ef2e6c.png)
 This is the error i am facing

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/227072012-00797a5e-5a4b-49e4-a7bd-a6e33f7e84e6.png)

**Comment by Thayalan21** [comment]
I did all the steps you guys provided starting from the flask and also the
frontend part let me share you the problems i am facing.The first picture
is on the frontend part of uploading section.And the second picture is
error in uploading part in flask app.

[image: image.png][image: image.png]

**Comment by Thayalan21** [comment]
These are the steps i did

1.Clone the file
2.In application folder i installed requirement.txt
3.I create env file with my api key
4.And i ran app.py

For the front end.

1.In the front-end folder I ran npm install
2. VITE_API_HOST=http://localhost:5001 i changed this in env development
3.And then i ran npm run dev But it still not working

**Comment by Thayalan21** [comment]
Also i find error in html parser in application folder

[image: image.png]

So i change the code accordingly

[image: image.png]

**Comment by dartpain** [comment]
We are updating our wiki, but to have upload functionality you need to launch with `docker-compose up `

**Comment by Thayalan21** [comment]
This error shows up after i ran docker-compose up 

/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by dartpain** [comment]
Try
`docker --version`
 
and 
`docker-compose --version.`

and submit your response

I think you may need to update them. Also changing version in your docker-compose.yaml file might help
on the top of the file substitute version: "3.9" to version: "3.3"

**Comment by Thayalan21** [comment]
/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
docker-compose version 1.25.0, build unknown/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
docker-compose version 1.25.0, build unknown


This is what i get after these steps

**Comment by Thayalan21** [comment]
![ima_574634b](https://user-images.githubusercontent.com/104500045/227456980-3a262de8-b310-4e65-a485-dc6bed934942.jpeg)


I tried to solve the problem with docker but i get this error in console when i tried to upload a pdf file.So still the upload function is not working. Is it just me or everybody have this issue?

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/227822810-618255ce-7961-4e85-874c-d08735145c24.png)
I am still receiving the errors. I managed to run this on docker but the the upload issue is not solving

**Comment by Thayalan21** [comment]
Hello people. I just wanna ask why this error pop up when I tried the uploading function. I've already launched this code in docker but still facing issues with the upload function

![image](https://user-images.githubusercontent.com/104500045/227875611-57a4dfa9-d5f5-4de1-b7a5-961805e3dcd2.png)

**Comment by Thayalan21** [comment]
@dartpain

**Comment by Thayalan21** [comment]
I've posted some issues in git hub.Do you mind checking sir?

**Comment by blindcoding9** [comment]
I`m facing the same error, running local.

**Comment by Thayalan21** [comment]
Is it because i am running these code on ssh proxmox server???

**Comment by Thayalan21** [comment]
Is it because i am running these code on ssh proxmox server???

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/228006482-29a7e035-59d9-48f5-b2fc-c826039a50a5.png)
![image](https://user-images.githubusercontent.com/104500045/228006647-6bcce92e-6c85-4245-b19b-2a25c1f0af37.png)

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/228006745-1b6305ff-a07b-4c61-a323-8cf82be7cb8a.png)

**Comment by dartpain** [comment]
Ok looks like its an issue with Mongo container connection

**Comment by Thayalan21** [comment]
Nope no difference

**Comment by dartpain** [comment]
https://www.mongodb.com/products/compass
This tool for example

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/228104118-9156689f-cfea-4bcb-ac4d-0682de89a512.png)
I am still receiving this error

**Comment by Thayalan21** [comment]
worker_1    | [2023-03-28 03:21:14,812: INFO/MainProcess] Task app.ingest[b4ffd974-eb01-4dce-8201-998af1483073] received
worker_1    | [2023-03-28 03:21:14,834: WARNING/ForkPoolWorker-4] Grouping small documents
worker_1    | [2023-03-28 03:21:14,841: WARNING/ForkPoolWorker-4] Separating large documents
worker_1    | [2023-03-28 03:21:14,845: WARNING/ForkPoolWorker-4] Grouping failed, try running without token_check
Embedding 🦖: |          | Time Left: ? WARNING/ForkPoolWorker-4] 
Embedding 🦖: |          | Time Left: ? WARNING/ForkPoolWorker-4] 
backend_1   | [2023-03-28 03:21:34 +0000] [6] [ERROR] Error handling request /api/combine
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1   |     self.handle_request(listener, req, client, addr)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1   |     respiter = self.wsgi(environ, resp.start_response)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
backend_1   |     return self.wsgi_app(environ, start_response)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
backend_1   |     response = self.handle_exception(e)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
backend_1   |     response = self.full_dispatch_request()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
backend_1   |     rv = self.handle_user_exception(e)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
backend_1   |     rv = self.dispatch_request()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
backend_1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
backend_1   |   File "/app/app.py", line 301, in combined_json
backend_1   |     for index in vectors_collection.find({'user': user}):
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1248, in next
backend_1   |     if len(self.__data) or self._refresh():
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1139, in _refresh
backend_1   |     self.__session = self.__collection.database.client._ensure_session()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
backend_1   |     return self.__start_session(True, causal_consistency=False)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
backend_1   |     self._topology._check_implicit_session_support()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
backend_1   |     self._check_session_support()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 554, in _check_session_support
backend_1   |     self._select_servers_loop(
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
backend_1   |     raise ServerSelectionTimeoutError(
backend_1   | pymongo.errors.ServerSelectionTimeoutError: mongo:27018: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 64225cb0716e4782aad2cafe, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27018: [Errno -3] Temporary failure in name resolution')>]>
backend_1   | [2023-03-28 03:21:45 +0000] [7] [ERROR] Error handling request /api/upload_index
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1   |     self.handle_request(listener, req, client, addr)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1   |     respiter = self.wsgi(environ, resp.start_response)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
backend_1   |     return self.wsgi_app(environ, start_response)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
backend_1   |     response = self.handle_exception(e)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
backend_1   |     response = self.full_dispatch_request()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
backend_1   |     rv = self.handle_user_exception(e)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
backend_1   |     rv = self.dispatch_request()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
backend_1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
backend_1   |   File "/app/app.py", line 395, in upload_index_files
backend_1   |     vectors_collection.insert_one({
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 628, in insert_one
backend_1   |     self._insert_one(
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 569, in _insert_one
backend_1   |     self.__database.client._retryable_write(acknowledged, _insert_command, session)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
backend_1   |     with self._tmp_session(session) as s:
backend_1   |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
backend_1   |     return next(self.gen)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
backend_1   |     s = self._ensure_session(session)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
backend_1   |     return self.__start_session(True, causal_consistency=False)
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
backend_1   |     self._topology._check_implicit_session_support()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
backend_1   |     self._check_session_support()
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 554, in _check_session_support
backend_1   |     self._select_servers_loop(
backend_1   |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
backend_1   |     raise ServerSelectionTimeoutError(
backend_1   | pymongo.errors.ServerSelectionTimeoutError: mongo:27018: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 64225cb0f674f18d0522572d, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27018: [Errno -3] Temporary failure in name resolution')>]>
worker_1    | [2023-03-28 03:21:45,957: INFO/ForkPoolWorker-4] Task app.ingest[b4ffd974-eb01-4dce-8201-998af1483073] succeeded in 31.138961516000563s: {'directory': 'temp', 'formats': ['.rst', '.md', '.pdf', '.txt'], 'name_job': 'sample-essay-1_1.rst', 'filename': 'sample-essay-1_1.rst', 'user': 'local', 'limited': False}

**Comment by Thayalan21** [comment]
This happens in the log

**Comment by dartpain** [comment]
Please check if there are any logs for mongo_1 container.
Send me docker-compose.yaml file (remove the api keys from there too please)

**Comment by dartpain** [comment]
Do you lanuch it with docker-compose up?
Do you have any container logs for mongo?

**Comment by Thayalan21** [comment]
Yes i did launch it with docker-compose up. But the mongodb seem to not work. I've also tried to use external momgodb but still it does not work

**Comment by dartpain** [comment]
Interesting, seems like it can't start a container for mongodb then.
Try `docker --version`

**Comment by Thayalan21** [comment]
yeah docker is installed

**Comment by Thayalan21** [comment]
Sir i managed to do it Thank you. But is the token issue is still there right? Because i use document it print nothing.I attach the file here

**Comment by Thayalan21** [comment]
[vertopal.com_Never-Split-the-Difference (1).zip](https://github.com/arc53/DocsGPT/files/11097344/vertopal.com_Never-Split-the-Difference.1.zip)

**Comment by Thayalan21** [comment]
Issue resolved thanks

**Comment by Thayalan21** [comment]
Is it possible if we could upload multiple files?

**Comment by dartpain** [comment]
As a zip you can, im closing this issue
