### ISSUE TITLE
openai.error.APIConnectionError when asking a question to a document

### ISSUE THREAD

**Issue by RikSchoonbeek** [arc53/DocsGPT#276]
In the development environment, as set up using the instructions [here](https://github.com/arc53/DocsGPT#development-environments), when asking a question to a document an openai.error.APIConnectionError occurs. To be complete, it's a POST request to `http://localhost:7091/api/answer` in which the error occurs. See Traceback below.

The cause seems to be the clashing of the variable name OPENAI_API_BASE used in DocsGPT and the variable name used by the openai Python package. Another project had the same issue, [see here](https://github.com/Significant-Gravitas/Auto-GPT/pull/648).

This can be solved simply by renaming OPENAI_API_BASE as used in the DocsGPT code to another name, like OPENAI_AZURE_API_BASE.

I already made the changes locally and will make a PR, as other people seem to run into the same issue, see:
https://discord.com/channels/1070046503302877216/1070605825112035399/1118266133305376869
https://discord.com/channels/1070046503302877216/1070605825112035399/1118296369883512864

Error Traceback:
```
Traceback (most recent call last):
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/openai/api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/engines/text-embedding-ada-002/embeddings': No scheme supplied. Perhaps you meant https:///engines/text-embedding-ada-002/embeddings?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rik/projects/DocsGPT2/application/app.py", line 326, in api_answer
    result = run_async_chain(chain, question, chat_history)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/projects/DocsGPT2/application/app.py", line 109, in run_async_chain
    answer = loop.run_until_complete(async_generate(chain, question, chat_history))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rik/projects/DocsGPT2/application/app.py", line 100, in async_generate
    result = await chain.arun({"question": question, "chat_history": chat_history})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/chains/base.py", line 300, in arun
    return (await self.acall(args[0], callbacks=callbacks, tags=tags))[
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/chains/base.py", line 198, in acall
    raise e
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/chains/base.py", line 192, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 144, in _acall
    docs = await self._aget_docs(new_question, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 195, in _aget_docs
    docs = await self.retriever.aget_relevant_documents(question)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 410, in aget_relevant_documents
    docs = await self.vectorstore.asimilarity_search(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 199, in asimilarity_search
    return await asyncio.get_event_loop().run_in_executor(None, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 303, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 244, in similarity_search_with_score
    embedding = self.embedding_function(query)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 316, in embed_query
    embedding = self._embedding_func(text, engine=self.deployment)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 282, in _embedding_func
    return embed_with_retry(
           ^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 64, in embed_with_retry
    return _embed_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 62, in _embed_with_retry
    return embeddings.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/openai/api_requestor.py", line 288, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "/home/rik/.virtualenvs/DocsGPT2/lib/python3.11/site-packages/openai/api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL '/engines/text-embedding-ada-002/embeddings': No scheme supplied. Perhaps you meant https:///engines/text-embedding-ada-002/embeddings?
127.0.0.1 - - [08/Jul/2023 17:37:59] "POST /api/answer HTTP/1.1" 500 -
Error communicating with OpenAI: Invalid URL '/engines/text-embedding-ada-002/embeddings': No scheme supplied. Perhaps you meant https:///engines/text-embedding-ada-002/embeddings?
```

**Comment by dartpain** [comment]
Solved in #278 
Thank you!
