### ISSUE TITLE
List index out of range when executing ingest_rst.py

### ISSUE THREAD

**Issue by ivfarias** [arc53/DocsGPT#51]
After adding a file to /scripts/inputs I get the following error when running ingest_rst.py. Any ideas?

```
Traceback (most recent call last):
  File "/Users/ivan/Documents/dev/DocsGPT/scripts/ingest_rst.py", line 85, in <module>
    get_user_permission()
  File "/Users/ivan/Documents/dev/DocsGPT/scripts/ingest_rst.py", line 38, in get_user_permission
    call_openai_api()
  File "/Users/ivan/Documents/dev/DocsGPT/scripts/ingest_rst.py", line 21, in call_openai_api
    store = FAISS.from_texts(docs, OpenAIEmbeddings(), metadatas=metadatas)
  File "/Users/ivan/.local/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 192, in from_texts
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range
```

**Comment by jaredbradley243** [comment]
Hey! @ivfarias ,

If you haven't already, in the folder named "_**scikit-learn**_" inside the "_**scripts**_" folder, toss your **.rst**.

Then run either _**ingest_rst.py**_ or _**ingest_rst_sphinx.py**_ using the following commands:

```python ingest_rst.py -i scikit-learn```

```python ingest_rst_sphinx.py -i scikit-learn```

Make sure you have your **.env** file in the "_**scripts**_" folder.

![image](https://user-images.githubusercontent.com/107898107/217945694-e966c351-5f73-4a8a-a219-e6dcdda14de0.png)

I'm going to close this issue now, feel free to reopen it if you still get the same error! 😎
