### ISSUE TITLE
🐛 Bug Report: Error communicating with OpenAI when upload a file

### ISSUE THREAD

**Issue by idchangyifan** [arc53/DocsGPT#562]
### 📜 Description

It bugs when i run DocsGPT in dev mode and upload a file.

### 👟 Reproduction steps

i followed the readme file

### 👍 Expected behavior

it should upload successful

### 👎 Actual Behavior with Screenshots

it actually return errors

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

API_KEY
EMBEDDINGS_KEY
API_URL
FLASK_APP
FLASK_DEBUG

### 📖 Relevant log output

```shell
celery log:
[2023-10-11 07:13:41,670: WARNING/ForkPoolWorker-2] Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: Invalid URL '/embeddings': No scheme supplied. Perhaps you meant https:///embeddings?.

Arguments: {'hostname': 'celery@vultr', 'id': '5842508f-8c88-443e-a2f1-e016ee7f5a2e', 'name': 'application.api.user.tasks.ingest', 'exc': 'APIConnectionError(message="Error communicating with OpenAI: Invalid URL \'/embeddings\': No scheme supplied. Perhaps you meant https:///embeddings?", http_status=None, request_id=None)', 'traceback': 'Traceback (most recent call last):\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 596, in request_raw\n    result = _thread_context.session.request(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/requests/sessions.py", line 575, in request\n    prep = self.prepare_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request\n    p.prepare(\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/requests/models.py", line 368, in prepare\n    self.prepare_url(url, params)\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url\n    raise MissingSchema(\nrequests.exceptions.MissingSchema: Invalid URL \'/embeddings\': No scheme supplied. Perhaps you meant https:///embeddings?\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/api/user/tasks.py", line 6, in ingest\n    resp = ingest_worker(self, directory, formats, name_job, filename, user)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/worker.py", line 78, in ingest_worker\n    call_openai_api(docs, full_path, self)\n  File "/root/DocsGPT/application/parser/open_ai_func.py", line 41, in call_openai_api\n    store = VectorCreator.create_vectorstore(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/vectorstore/vector_creator.py", line 16, in create_vectorstore\n    return vectorstore_class(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/vectorstore/faiss.py", line 11, in __init__\n    self.docsearch = FAISS.from_documents(\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 422, in from_documents\n    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 602, in from_texts\n    embeddings = embedding.embed_documents(texts)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 490, in embed_documents\n    return self._get_len_safe_embeddings(texts, engine=self.deployment)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 374, in _get_len_safe_embeddings\n    response = embed_with_retry(\n               ^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 107, in embed_with_retry\n    return _embed_with_retry(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f\n    return self(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result\n    raise self._exception\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 104, in _embed_with_retry\n    response = embeddings.client.create(**kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create\n    response = super().create(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create\n    response, _, api_key = requestor.request(\n                           ^^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 288, in request\n    result = self.request_raw(\n             ^^^^^^^^^^^^^^^^^\n  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 609, in request_raw\n    raise error.APIConnectionError(\nopenai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL \'/embeddings\': No scheme supplied. Perhaps you meant https:///embeddings?\n', 'args': "['inputs', ['.rst', '.md', '.pdf', '.txt'], 'wenhui666.pdf', 'wenhui666.pdf', 'local']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}


flask log:
61.141.241.116 - - [11/Oct/2023 07:14:15] "GET /api/task_status?task_id=69bc8b78-f57f-4d18-bd36-62c4fac472d4 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/app.py", line 2157, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/root/DocsGPT/application/venv/lib/python3.11/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type APIConnectionError is not JSON serializable
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Are you using a remote server?

**Comment by idchangyifan** [comment]
> Are you using a remote server?

yes

**Comment by dartpain** [comment]
I think your openai key is a bit overused, just maybe wait a bit and it should work fine

**Comment by idchangyifan** [comment]
> I think your openai key is a bit overused, just maybe wait a bit and it should work fine

i'm afraid its not the real reason. i tried several times and it returned the same error.

In addition, when i tried the remote doc like pandas or python, it returned error too. There are the logs:

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open application/vectors/python/pandas/1.5.3/openai_text-embedding-ada-002/index.faiss for reading: No such file or directory

however, the file "application/vectors/python/pandas/1.5.3/openai_text-embedding-ada-002/index.faiss" exists.

**Comment by dartpain** [comment]
Hmmm looks like its not able to access the vectorstore.
Can you please describe in detail how did you launch docsgpt?

**Comment by idchangyifan** [comment]
> Hmmm looks like its not able to access the vectorstore. Can you please describe in detail how did you launch docsgpt?

i must missing someting because when i launch docsgpt in my mac, it returns the same error. 
i strictly follow the readme 'Development environments' part and every command runs well.
i've not run the setup.sh successfully but i think its ok when i check the command in it.

**Comment by idchangyifan** [comment]
> Hmmm looks like its not able to access the vectorstore. Can you please describe in detail how did you launch docsgpt?

i figure it out! 
The .env file cant keep the Azure config
