### ISSUE TITLE
`KeyError: 'source'` when using a custom doc

### ISSUE THREAD

**Issue by EperezOk** [arc53/DocsGPT#66]
Hi! I followed [this guide](https://github.com/arc53/docsgpt/wiki/How-to-train-on-other-documentation) to train the AI with my own documentation, which is a `.md` file.

I changed the `.rst` extensions I saw in `ingest_rst.py` and `ingest_rst_sphinx.py` to `.md` and that successfully generated the `docs.index` and `faiss_store.pkl` files wich I moved to the root of `/application`.

However, when using the `Default` option in the dropdown of the UI, I get a 500 response that says `KeyError: 'source'`.
Am I missing something?

**Comment by vintrocode** [comment]
getting the same error. it looks like it's a problem with langchain. here's the traceback:
```
 * Debugger is active!
 * Debugger PIN: 409-944-645
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/src/chat.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/src/choiceChange.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/src/authapi.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/dist/css/output.css HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/favicon/favicon-32x32.png HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:45] "GET /static/favicon//site.webmanifest HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2023 21:39:48] "POST /api/docs_check HTTP/1.1" 200 -
127.0.0.1 - - [10/Feb/2023 21:39:59] "POST /api/answer HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/vintro/work/plastic/DocsGPT/application/app.py", line 74, in api_answer
    result = chain({"question": question}, return_only_outputs=True)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/qa_with_sources/base.py", line 106, in _call
    answer, _ = self.combine_documents_chain.combine_docs(docs, **inputs)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/combine_documents/map_reduce.py", line 150, in combine_docs
    num_tokens = length_func(result_docs, **kwargs)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 77, in prompt_length
    inputs = self._get_inputs(docs, **kwargs)
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 64, in _get_inputs
    document_info = {
  File "/Users/vintro/.virtualenvs/docs-gpt-pycord/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 65, in <dictcomp>
    k: base_info[k] for k in self.document_prompt.input_variables
KeyError: 'source'
```
I can't quite pinpoint what the issue might be though. It looks like it's getting a `source` key in the input variables for the document prompt, but in line 69 of `app.py` you can see the only input variables are `["summaries", "question"]`.
