### ISSUE TITLE
Limit token size in the app while asking questions

### ISSUE THREAD

**Issue by zjrwtx** [arc53/DocsGPT#93]
![image](https://user-images.githubusercontent.com/86822589/219252992-5137d247-00e5-4ad6-8c97-b8603aa400a3.png)

**Comment by dartpain** [comment]
Have not seen this error in a while. Will try to replicate it:
1. Can you make sure you have latest version of repo, (run `git pull`)
2. Can you please send me the text that triggered this error, you can email it to me if you need more privacy?

**Comment by zjrwtx** [comment]
Traceback (most recent call last):
  File "D:\python\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\python\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "D:\python\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\30388\Desktop\DocsGPT-main\application\app.py", line 119, in api_answer
    result = chain({"query": question})
  File "D:\python\lib\site-packages\langchain\chains\base.py", line 142, in __call__
    raise e
  File "D:\python\lib\site-packages\langchain\chains\base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "D:\python\lib\site-packages\langchain\chains\vector_db_qa\base.py", line 153, in _call
    answer, _ = self.combine_documents_chain.combine_docs(docs, question=question)
  File "D:\python\lib\site-packages\langchain\chains\combine_documents\map_reduce.py", line 139, in combine_docs
    results = self.llm_chain.apply(
  File "D:\python\lib\site-packages\langchain\chains\llm.py", line 91, in apply
    response = self.generate(input_list)
  File "D:\python\lib\site-packages\langchain\chains\llm.py", line 59, in generate
    response = self.llm.generate(prompts, stop=stop)
  File "D:\python\lib\site-packages\langchain\llms\base.py", line 128, in generate
    raise e
  File "D:\python\lib\site-packages\langchain\llms\base.py", line 125, in generate
    output = self._generate(prompts, stop=stop)
  File "D:\python\lib\site-packages\langchain\llms\openai.py", line 217, in _generate
    response = self.completion_with_retry(prompt=_prompts, **params)
  File "D:\python\lib\site-packages\langchain\llms\openai.py", line 178, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "D:\python\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\python\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\python\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "D:\python\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\python\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\python\lib\site-packages\langchain\llms\openai.py", line 176, in _completion_with_retry
    return self.client.create(**kwargs)
  File "D:\python\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\python\lib\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\python\lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "D:\python\lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 7601 tokens (7345 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
 * Restarting with watchdog (windowsapi)
 * Debugger is active!
 * Debugger PIN: 503-849-649

**Comment by zjrwtx** [comment]
> Have not seen this error in a while. Will try to replicate it:
> 
> 1. Can you make sure you have latest version of repo, (run `git pull`)
> 2. Can you please send me the text that triggered this error, you can email it to me if you need more privacy?
i am sure it is the latest version repo

**Comment by dartpain** [comment]
Ahh, so its not at the ingestion stage. It happened while you where talking to it. We definitly need to adhere to limits. Its a bug

**Comment by dartpain** [comment]
What question did you ask it?
How big was it and what documentation did you load?

**Comment by zjrwtx** [comment]
> What question did you ask it? How big was it and what documentation did you load?

![image](https://user-images.githubusercontent.com/86822589/219356113-2281d190-8502-4d98-abc9-b6170d01a764.png)
my rst file size

**Comment by dartpain** [comment]
And how big was the question you asked? how many characters?

**Comment by zjrwtx** [comment]
> And how big was the question you asked? how many characters?

just one word

**Comment by chinesewebman** [comment]
I have had the same error [#145](https://github.com/arc53/DocsGPT/issues/145) but it being fixed well now.
