### ISSUE TITLE
No module named 'llama_cpp' issue, but it actually has

### ISSUE THREAD

**Issue by wo4wangle** [arc53/DocsGPT#930]
### 📜 Description

No module named 'llama_cpp' issue, but it actually has llama_cpp

### 👟 Reproduction steps

1. Source Docs select default
2. type "hi" in chat box
3. enter 

### 👍 Expected behavior

normally response 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/46141646/086e238c-1a13-4c27-9552-c9cd685b1ee8)

resoponse with "Something went wrong. Please try again later."

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

LLM_NAME=llama.cpp
EMBEDDINGS_NAME=huggingface_sentence-transformers/all-mpnet-base-v2
VITE_API_STREAMING=true

### 📃 Provide any additional context for the Bug.

```
llama-cpp-python actually installed, both python virtual/system env  (DocsGPT run on virtual python env)

[root@xxx-alma8 DocsGPT]# source venv/bin/a
-bash: venv/bin/a: No such file or directory
[root@xxx-alma8 DocsGPT]# source venv/bin/activate
(venv) [root@xxx-alma8 DocsGPT]# pip install llama-cpp-python
Requirement already satisfied: llama-cpp-python in ./venv/lib64/python3.11/site-packages (0.2.65)
Requirement already satisfied: typing-extensions>=4.5.0 in ./venv/lib/python3.11/site-packages (from llama-cpp-python) (4.11.0)
Requirement already satisfied: numpy>=1.20.0 in ./venv/lib64/python3.11/site-packages (from llama-cpp-python) (1.26.4)
Requirement already satisfied: diskcache>=5.6.1 in ./venv/lib/python3.11/site-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in ./venv/lib/python3.11/site-packages (from llama-cpp-python) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib64/python3.11/site-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.5)

[root@xxx-alma8 ~]# pip install llama-cpp-python
Requirement already satisfied: llama-cpp-python in /usr/local/lib64/python3.11/site-packages (0.2.65)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (4.11.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib64/python3.11/site-packages (from llama-cpp-python) (1.26.4)
Requirement already satisfied: diskcache>=5.6.1 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib64/python3.11/site-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@xxx-alma8 ~]#
```

### 📖 Relevant log output

```shell
backend-1   | [2024-04-27 07:12:40 +0000] [7] [ERROR] Error handling request /stream
backend-1   | Traceback (most recent call last):
backend-1   |   File "/app/application/llm/llama_cpp.py", line 17, in __init__
backend-1   |     from llama_cpp import Llama
backend-1   | ModuleNotFoundError: No module named 'llama_cpp'
backend-1   |
backend-1   | During handling of the above exception, another exception occurred:
backend-1   |
backend-1   | Traceback (most recent call last):
backend-1   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 135, in handle
backend-1   |     self.handle_request(listener, req, client, addr)
backend-1   |  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 183, in handle_request
backend-1   |     for item in respiter:
backend-1   |   File "/usr/local/lib/python3.11/site-packages/werkzeug/wsgi.py", line 256, in __next__
backend-1   |     return self._next()
backend-1   |            ^^^^^^^^^^^^
backend-1   |  File "/usr/local/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
backend-1   |     for item in iterable:
backend-1   |   File "/app/application/api/answer/routes.py", line 179, in complete_stream
backend-1   |     for line in answer:
backend-1   |   File "/app/application/retriever/classic_rag.py", line 101, in gen
backend-1   |     llm = LLMCreator.create_llm(
backend-1   |           ^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/app/application/llm/llm_creator.py", line 27, in create_llm
backend-1   |     return llm_class(api_key, user_api_key, *args, **kwargs)
backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/app/application/llm/llama_cpp.py", line 19, in __init__
backend-1   |     raise ImportError(
backend-1   | ImportError: Please install llama_cpp using pip install llama-cpp-python
```
```


### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wo4wangle** [comment]
just install it in container will solve
