### ISSUE TITLE
openai.error.InvalidRequestError when using custom documentation

### ISSUE THREAD

**Issue by liammazy** [arc53/DocsGPT#97]
I followed [the instructions](https://github.com/arc53/docsgpt/wiki/How-to-train-on-other-documentation) to train my own documents, but the generated index file was named "index.faiss" and "index.pkl" instead of "docs.index" and "faiss_store.pkl". After copying the generated files to the application directory and running `app.py`, I encountered the following error message when asking questions:

>Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/liam.mazy/Developer/DocsGPT/application/app.py", line 129, in api_answer
    result = chain({"query": question})
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/vector_db_qa/base.py", line 153, in _call
    answer, _ = self.combine_documents_chain.combine_docs(docs, question=question)
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/combine_documents/map_reduce.py", line 139, in combine_docs
    results = self.llm_chain.apply(
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 91, in apply
    response = self.generate(input_list)
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 59, in generate
    response = self.llm.generate(prompts, stop=stop)
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 128, in generate
    raise e
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 125, in generate
    output = self._generate(prompts, stop=stop)
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py", line 217, in _generate
    response = self.completion_with_retry(prompt=_prompts, **params)
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py", line 178, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py", line 176, in _completion_with_retry
    return self.client.create(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 8745 tokens (8489 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

It seems that the application is not recognizing my custom index file. I'm not sure if I missed any steps or if there is a problem with the instructions.

**Comment by dartpain** [comment]
Hi, we recently changed a lot in how indexes are generated, sorry for inconvenience. To resolve this issue just update your app. You can do this by writing `git pull` in your terminal in the directory of docsgpt

**Comment by liammazy** [comment]
The files I used for training are in `.md` format. Additionally, I just updated the project using `git pull`, but I'm still encountering the issue mentioned above.

**Comment by dartpain** [comment]
Try updating with git pull, re -ingesting data and seeing if the issue still exists please

**Comment by chinesewebman** [comment]
i have had the same error [#145 ](url) but now it is fixed well.
