### ISSUE TITLE
🐛 Bug Report: Can not Run the Backend

### ISSUE THREAD

**Issue by yilifeng** [arc53/DocsGPT#976]
### 📜 Description

run in backend  error

### 👟 Reproduction steps

Run the Backend

Note

Make sure you have Python 3.10 or 3.11 installed.

    Export required environment variables or prepare a .env file in the project folder:
        Copy [.env_sample](https://github.com/arc53/DocsGPT/blob/main/application/.env_sample) and create .env.

(check out [application/core/settings.py](https://github.com/arc53/DocsGPT/blob/main/application/core/settings.py) if you want to see more config options.)

    (optional) Create a Python virtual environment: You can follow the [Python official documentation](https://docs.python.org/3/tutorial/venv.html) for virtual environments.

a) On Mac OS and Linux

python -m venv venv
. venv/bin/activate

b) On Windows

python -m venv venv
 venv/Scripts/activate

    Download embedding model and save it in the model/ folder: You can use the script below, or download it manually from [here](https://d3dg1063dc54p9.cloudfront.net/models/embeddings/mpnet-base-v2.zip), unzip it and save it in the model/ folder.

wget https://d3dg1063dc54p9.cloudfront.net/models/embeddings/mpnet-base-v2.zip
unzip mpnet-base-v2.zip -d model
rm mpnet-base-v2.zip

    Install dependencies for the backend:

pip install -r application/requirements.txt

    Run the app using flask --app application/app.py run --host=0.0.0.0 --port=7091.
    Start worker with celery -A application.app.celery worker -l INFO.

### 👍 Expected behavior

Expect Flask to start normally

### 👎 Actual Behavior with Screenshots

(DocsGPT_1) mvt001@ubuntu-001:~/ylf/DocsGPT$ flask --app application/app.py run --host=0.0.0.0 --port=7091
Traceback (most recent call last):
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/flask/cli.py", line 953, in run_command
    raise e from None
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/flask/cli.py", line 337, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/flask/cli.py", line 247, in locate_app
    __import__(module_name)
  File "/home/mvt001/ylf/DocsGPT/application/app.py", line 3, in <module>
    from application.celery import celery
  File "/home/mvt001/ylf/DocsGPT/application/celery.py", line 2, in <module>
    from application.core.settings import settings
  File "/home/mvt001/ylf/DocsGPT/application/core/settings.py", line 70, in <module>
    settings = Settings(_env_file=path.joinpath(".env"), _env_file_encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/home/mvt001/anaconda3/envs/DocsGPT_1/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
flask_app
  Extra inputs are not permitted [type=extra_forbidden, input_value='application/app.py', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
flask_debug
  Extra inputs are not permitted [type=extra_forbidden, input_value='true', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yilifeng** [comment]
Deploying Docker with the same error message

![image](https://github.com/arc53/DocsGPT/assets/19308459/2ba3ce69-3d73-4b7a-9182-90e9f9b347d6)

**Comment by yilifeng** [comment]
The problem has been resolved: 1. There is a cellery.py file with the same name as the dependency library in the code, and the file name has been changed;
The. env file in the application directory cannot be created and should be deleted
